# git push sc master => runs CI
#
# git tag v0.1.2
# git push sc --tags => creates package and uploads to Nexus

# image: python:3.12.3-slim-bullseye@sha256:6fa552fb879325884b0c1b6792d14ae9500d246c8b19cc27876d84c7c41117ff
image: ghcr.io/astral-sh/uv:python3.12-bookworm@sha256:49557779236dbb588107b5b93d3af67a6da18f5912c5a306b357265e1688fa01

stages:
  - test
  - deploy

before_script:
   - uv venv
   - source .venv/bin/activate && which python
   - uv pip install --upgrade pip
   - uv pip install pytest twine

tests:
  stage: test
  script:
    # XXX: can we remove this?
    - source .venv/bin/activate
    - uv pip install python-daemon --index-url $PYPI_PROXY_URL # error: setuptools 57.4.0 is installed but setuptools>=62.4.0 is required by {'python-daemon'}
    - uv pip install backports.csv # try installing this from pypi, nexus may not like the [.]
    - uv pip install iso-639 # try installing this from pypi, nexus may not like the [.]
    - uv pip install pybind11 # via duckdb error
    # - python setup.py develop --index-url $PYPI_PROXY_URL # faster, less load for pypi
    - uv sync --all-groups --all-extras
    - which python
    - which pytest
    - uv run pytest
  tags: [docker]
  except:
    - tags

upload_to_nexus:
  stage: deploy
  variables:
    TWINE_USERNAME: $NEXUS_USERNAME
    TWINE_PASSWORD: $NEXUS_PASSWORD
  script:
    # - python setup.py sdist
    - uv build
    - uv run twine upload --repository-url $NEXUS_REPOSITORY_URL dist/*
  only:
    - tags
  tags: [docker]
