image: python:3.6.9-buster

stages:
  - test
  - deploy

before_script:
   - pip install pytest twine
   - python setup.py develop --index-url $PYPI_PROXY_URL # for tests, use nexus proxy for installing packages
   - python setup.py sdist   # for packaging

tests:
  stage: test
  script:
  - pytest
  tags: [docker]

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $NEXUS_USERNAME
    TWINE_PASSWORD: $NEXUS_PASSWORD
  script:
    - twine upload --repository-url $NEXUS_REPOSITORY_URL dist/*
  only:
    - tags
  tags: [docker]
