image: python:3.6-alpine

stages:
  - test
  - deploy

before_script:
   - pip install twine
   - pip install pytest
   - python setup.py sdist

tests:
  stage: test
  script:
  - pytest
  tags: [docker]

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $NEXUS_USERNAME
    TWINE_PASSWORD: $NEXUS_PASSWORD
  script:
    - twine upload --repository-url $NEXUS_REPOSITORY_URL dist/*
  only:
    - tags
  tags: [docker]
