all:
	@echo "usage: python partP_NAME.py"
	@echo
	@echo "run 'make clean-P' to clean generated data for a part P" 

clean-1:
	rm -rf output/1

clean-2:
	rm -rf output/2

clean-3:
	rm -rf output/3

clean-4:
	rm -rf output/4

clean-5:
	rm -rf output/5

clean-6:
	rm -rf output/6

clean:
	find . -name "*.DS_Store" -exec rm -f {} \;
	find . -name "*pyc" -exec rm -f {} \;

clean-all-artifacts:
	rm -rf output
