# Linux distro as of 11/2022 is Fedora
- name: Install common packages
  dnf:
    state: present
    name:
    - bash-completion
    - bc
    - bind-utils # for nslookup, etc.
    - btop
    - bzip2
    - cowsay
    - cpufetch
    - cronie # https://stackoverflow.com/a/21802522/89391
    - curl
    - fd-find
    - fortune-mod
    - git
    - git-extras
    - glances
    - golang
    - htop
    - iotop
    - jq
    - lftp
    - logrotate
    - lsof
    - mariadb-server # for replace: https://mariadb.com/kb/en/replace-utility/
    - moreutils # e.g. for "sponge"
    - multitail
    - ncdu
    - neofetch
    - netcat
    - nvme-cli
    - p7zip
    - p7zip-plugins
    - parallel
    - pigz
    # TODO: pip needs to be changed to use the correct python version as well; https://discussion.fedoraproject.org/t/is-it-possible-to-install-pip-for-older-versions-of-python/71371
    - pv
    - python3-devel
    - python3.12
    - python3.12-devel
    - python3.13 # fedora 43 ships with 3.14 by default, some pypi packages require 3.13 (e.g. "lingua-language-detector")
    - python3.13-devel # fedora 43 ships with 3.14 by default, some pypi packages require 3.13 (e.g. "lingua-language-detector")
    - ranger
    - rclone
    - ripgrep
    - rsync
    - screen
    - sl
    - smartmontools
    - sqlite
    - sysstat
    - tar
    - tmux
    - tree
    - unzip
    - uv
    - vim-enhanced
    - wget
    - z
    - zstd
- name: Register Python 3.12 with alternatives
  command:
    cmd: /usr/sbin/alternatives --install /usr/bin/python python /usr/bin/python3.12 3
- name: Register Python 3.13 with alternatives
  command:
    cmd: /usr/sbin/alternatives --install /usr/bin/python python /usr/bin/python3.13 4
- name: Set Python 3.13 as default
  command: /usr/sbin/alternatives --set python /usr/bin/python3.12
- name: Clean motd
  command: truncate -s 0 /etc/motd
- name: Enable services # https://stackoverflow.com/a/37633887/89391
  service:
    name: '{{ item }}'
    enabled: yes
  with_items:
  - crond
- name: Increase histsize
  copy:
    dest: /etc/profile.d/histsize.sh
    content: |
      export HISTSIZE=1000000
      export HISTFILESIZE=67108864
