# OS as of 11/2022 is Fedore 35
- name: Install common packages
  dnf:
    state: present
    name:
    - bash-completion
    - bc
    - bind-utils # for nslookup, etc.
    - btop
    - bzip2
    - cronie # https://stackoverflow.com/a/21802522/89391
    - curl
    - fd-find
    - git
    - glances
    - htop
    - iotop
    - jq
    - lftp
    - logrotate
    - lsof
    - moreutils
    - multitail
    - ncdu
    - neofetch
    - netcat
    - p7zip
    - p7zip-plugins
    - parallel
    - pigz
    - pv
    - ranger
    - rclone
    - ripgrep
    - rsync
    - screen
    - sqlite
    - tar
    - tmux
    - tree
    - unzip
    - vim-enhanced
    - wget
    - z
    - zstd
- name: Clean motd
  command: truncate -s 0 /etc/motd
- name: Enable services # https://stackoverflow.com/a/37633887/89391
  service:
    name: '{{ item }}'
    enabled: yes
  with_items:
  - crond
