# User and group for siskin
siskin_user: finc
siskin_group: finc

# Temporary directory, set system wide
siskin_tmp_dir: /data/tmp
# Static files can live here
siskin_static_dir: /data/static
# XDG cache dir for applications
siskin_cache_dir: /data/.cache
# Base directory for all raw and intermediate data files (TODO: maybe reuse ".cache")
siskin_data_dir: /data/finc

# Proxy settings, may need tweaks
siskin_proxy: http://proxy.uni-leipzig.de:3128
siskin_no_proxy: "127.0.0.1,services.ub.uni-leipzig.de,localhost,amsl.technology,live.amsl.technology,172.18.113.15,172.18.113.7,172.18.113.98,172.18.113.99"

# PyPI mirror, where we upload siskin
siskin_pypi_index_url: https://services.ub.uni-leipzig.de/nexus/repository/pypi/simple/

# Versions of custom packages
siskin_vendor_version_filterline: 0.1.5
siskin_vendor_version_groupcover: 0.0.12
siskin_vendor_version_metha: 0.2.49
siskin_vendor_version_siskin: 1.5.65
siskin_vendor_version_solrbulk: 0.3.8
siskin_vendor_version_solrdump: 0.1.7
siskin_vendor_version_span: 0.1.351
siskin_vendor_version_unzippa: 0.1.6

# Versions of extra packages
siskin_extra_version_duckdb: 0.8.1

