# TODO: switch to internal artifact servers or use a tunnel
#
- name: "Ensure group finc exists"
  group:
    name: "finc"
    state: present

- name: "Create service worker"
  user:
    name: "finc"
    group: "finc"
    shell: /bin/bash
    create_home: true

- name: "Install required packages for siskin"
  yum:
    state: present
    disable_gpg_check: true
    name:
      - sshuttle
      - https://github.com/miku/solrbulk/releases/download/v0.3.6/solrbulk-0.3.6-0.x86_64.rpm
      - https://github.com/ubleipzig/solrdump/releases/download/v0.1.7/solrdump-0.1.7-0.x86_64.rpm
      - https://github.com/miku/span/releases/download/v0.1.336/span-0.1.336-0.x86_64.rpm

- name: Execute task with extended PATH
  shell: echo $PATH
  environment:
    PATH: "/usr/other/bin:{{ ansible_env.PATH }}"

- name: "Change crossref cache directory ownership"
  file:
    path: "/data/finc"
    owner: "finc"
    group: "finc"
    state: directory
    mode: '0755'


- name: "Creates an entry like `PATH=/opt/bin:...` on top of crontab"
  cron:
    name: PATH
    user: "finc"
    env: true
    job: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

- name: "Crontab for crossref API sync"
  cron:
    name: Crossref API sync
    user: "finc"
    hour: "0"
    minute: "5"
    job: >
      span-crossref-sync -p zstd -c /data/finc/crossref -t 45m -mode s -verbose -s 2022-01-01 > /dev/null

